### ISSUE TITLE
not found uploadfont.js file

### ISSUE THREAD

**Issue by risnandar** [FPVTools/BitsyOSD#1]
but there is fontupload.js, executing the file generating errors like this

```
Rikis-MacBook-i5:font risn$ node fontupload.js 
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/risn/Downloads/BitsyOSD-1.2.0/font/node_modules/serialport/build/serialport/v1.6.3/Release/node-v46-darwin-x64/serialport.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/risn/Downloads/BitsyOSD-1.2.0/font/node_modules/serialport/serialport.js:14:25)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

im using latest version 1.2.0 and compile with osx

**Comment by flyandi** [comment]
Delete the node_modules folder and run npm install again - which should resolve the issue.
